apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tidyvanity.fullname" . }}-environment
  labels:
    {{- include "tidyvanity.labels" . | nindent 4 }}
data:
{{ toYaml .Values.env | indent 2 }}