/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTenent
 */
export interface CreateTenent {
    /**
     * 
     * @type {string}
     * @memberof CreateTenent
     */
    algorithm?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTenent
     */
    authorizationWebsite?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTenent
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTenent
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTenent
     */
    emailEndpoint?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTenent
     */
    expiresInSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateTenent
     */
    passwordResetExpiresInSeconds?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTenent
     */
    phoneNumberEndpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTenent
     */
    privateKey?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTenent
     */
    publicKey?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTenent
     */
    refreshExpiresInSeconds?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTenent
     */
    registrationWebsite?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTenent
     */
    uri: string;
}

/**
 * Check if a given object implements the CreateTenent interface.
 */
export function instanceOfCreateTenent(value: object): boolean {
    if (!('description' in value)) return false;
    if (!('uri' in value)) return false;
    return true;
}

export function CreateTenentFromJSON(json: any): CreateTenent {
    return CreateTenentFromJSONTyped(json, false);
}

export function CreateTenentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTenent {
    if (json == null) {
        return json;
    }
    return {
        
        'algorithm': json['algorithm'] == null ? undefined : json['algorithm'],
        'authorizationWebsite': json['authorization_website'] == null ? undefined : json['authorization_website'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'description': json['description'],
        'emailEndpoint': json['email_endpoint'] == null ? undefined : json['email_endpoint'],
        'expiresInSeconds': json['expires_in_seconds'] == null ? undefined : json['expires_in_seconds'],
        'passwordResetExpiresInSeconds': json['password_reset_expires_in_seconds'] == null ? undefined : json['password_reset_expires_in_seconds'],
        'phoneNumberEndpoint': json['phone_number_endpoint'] == null ? undefined : json['phone_number_endpoint'],
        'privateKey': json['private_key'] == null ? undefined : json['private_key'],
        'publicKey': json['public_key'] == null ? undefined : json['public_key'],
        'refreshExpiresInSeconds': json['refresh_expires_in_seconds'] == null ? undefined : json['refresh_expires_in_seconds'],
        'registrationWebsite': json['registration_website'] == null ? undefined : json['registration_website'],
        'uri': json['uri'],
    };
}

export function CreateTenentToJSON(value?: CreateTenent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'algorithm': value['algorithm'],
        'authorization_website': value['authorizationWebsite'],
        'client_id': value['clientId'],
        'description': value['description'],
        'email_endpoint': value['emailEndpoint'],
        'expires_in_seconds': value['expiresInSeconds'],
        'password_reset_expires_in_seconds': value['passwordResetExpiresInSeconds'],
        'phone_number_endpoint': value['phoneNumberEndpoint'],
        'private_key': value['privateKey'],
        'public_key': value['publicKey'],
        'refresh_expires_in_seconds': value['refreshExpiresInSeconds'],
        'registration_website': value['registrationWebsite'],
        'uri': value['uri'],
    };
}

