/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelValidateMFAST
 */
export interface ModelValidateMFAST {
    /**
     * 
     * @type {string}
     * @memberof ModelValidateMFAST
     */
    code: string;
}

/**
 * Check if a given object implements the ModelValidateMFAST interface.
 */
export function instanceOfModelValidateMFAST(value: object): boolean {
    if (!('code' in value)) return false;
    return true;
}

export function ModelValidateMFASTFromJSON(json: any): ModelValidateMFAST {
    return ModelValidateMFASTFromJSONTyped(json, false);
}

export function ModelValidateMFASTFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelValidateMFAST {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function ModelValidateMFASTToJSON(value?: ModelValidateMFAST | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
    };
}

