/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelPasswordResetST
 */
export interface ModelPasswordResetST {
    /**
     * 
     * @type {string}
     * @memberof ModelPasswordResetST
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ModelPasswordResetST
     */
    passwordConfirmation: string;
    /**
     * 
     * @type {string}
     * @memberof ModelPasswordResetST
     */
    token: string;
}

/**
 * Check if a given object implements the ModelPasswordResetST interface.
 */
export function instanceOfModelPasswordResetST(value: object): boolean {
    if (!('password' in value)) return false;
    if (!('passwordConfirmation' in value)) return false;
    if (!('token' in value)) return false;
    return true;
}

export function ModelPasswordResetSTFromJSON(json: any): ModelPasswordResetST {
    return ModelPasswordResetSTFromJSONTyped(json, false);
}

export function ModelPasswordResetSTFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelPasswordResetST {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
        'passwordConfirmation': json['passwordConfirmation'],
        'token': json['token'],
    };
}

export function ModelPasswordResetSTToJSON(value?: ModelPasswordResetST | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'password': value['password'],
        'passwordConfirmation': value['passwordConfirmation'],
        'token': value['token'],
    };
}

