/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhoneNumber
 */
export interface PhoneNumber {
    /**
     * 
     * @type {number}
     * @memberof PhoneNumber
     */
    applicationId: number;
    /**
     * 
     * @type {boolean}
     * @memberof PhoneNumber
     */
    confirmed: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PhoneNumber
     */
    createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof PhoneNumber
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PhoneNumber
     */
    phoneNumber: string;
    /**
     * 
     * @type {Date}
     * @memberof PhoneNumber
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the PhoneNumber interface.
 */
export function instanceOfPhoneNumber(value: object): boolean {
    if (!('applicationId' in value)) return false;
    if (!('confirmed' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('id' in value)) return false;
    if (!('phoneNumber' in value)) return false;
    if (!('updatedAt' in value)) return false;
    return true;
}

export function PhoneNumberFromJSON(json: any): PhoneNumber {
    return PhoneNumberFromJSONTyped(json, false);
}

export function PhoneNumberFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhoneNumber {
    if (json == null) {
        return json;
    }
    return {
        
        'applicationId': json['application_id'],
        'confirmed': json['confirmed'],
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'phoneNumber': json['phone_number'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function PhoneNumberToJSON(value?: PhoneNumber | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'application_id': value['applicationId'],
        'confirmed': value['confirmed'],
        'created_at': ((value['createdAt']).toISOString()),
        'id': value['id'],
        'phone_number': value['phoneNumber'],
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

