/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProtocolAuthenticatorAttachment = {
    Platform: 'platform',
    CrossPlatform: 'cross-platform'
} as const;
export type ProtocolAuthenticatorAttachment = typeof ProtocolAuthenticatorAttachment[keyof typeof ProtocolAuthenticatorAttachment];


export function ProtocolAuthenticatorAttachmentFromJSON(json: any): ProtocolAuthenticatorAttachment {
    return ProtocolAuthenticatorAttachmentFromJSONTyped(json, false);
}

export function ProtocolAuthenticatorAttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProtocolAuthenticatorAttachment {
    return json as ProtocolAuthenticatorAttachment;
}

export function ProtocolAuthenticatorAttachmentToJSON(value?: ProtocolAuthenticatorAttachment | null): any {
    return value as any;
}

