/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProtocolAuthenticatorTransport = {
    USB: 'usb',
    NFC: 'nfc',
    BLE: 'ble',
    Hybrid: 'hybrid',
    Internal: 'internal'
} as const;
export type ProtocolAuthenticatorTransport = typeof ProtocolAuthenticatorTransport[keyof typeof ProtocolAuthenticatorTransport];


export function ProtocolAuthenticatorTransportFromJSON(json: any): ProtocolAuthenticatorTransport {
    return ProtocolAuthenticatorTransportFromJSONTyped(json, false);
}

export function ProtocolAuthenticatorTransportFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProtocolAuthenticatorTransport {
    return json as ProtocolAuthenticatorTransport;
}

export function ProtocolAuthenticatorTransportToJSON(value?: ProtocolAuthenticatorTransport | null): any {
    return value as any;
}

