/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProtocolConveyancePreference = {
    PreferNoAttestation: 'none',
    PreferIndirectAttestation: 'indirect',
    PreferDirectAttestation: 'direct',
    PreferEnterpriseAttestation: 'enterprise'
} as const;
export type ProtocolConveyancePreference = typeof ProtocolConveyancePreference[keyof typeof ProtocolConveyancePreference];


export function ProtocolConveyancePreferenceFromJSON(json: any): ProtocolConveyancePreference {
    return ProtocolConveyancePreferenceFromJSONTyped(json, false);
}

export function ProtocolConveyancePreferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProtocolConveyancePreference {
    return json as ProtocolConveyancePreference;
}

export function ProtocolConveyancePreferenceToJSON(value?: ProtocolConveyancePreference | null): any {
    return value as any;
}

