/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProtocolUserVerificationRequirement = {
    VerificationRequired: 'required',
    VerificationPreferred: 'preferred',
    VerificationDiscouraged: 'discouraged'
} as const;
export type ProtocolUserVerificationRequirement = typeof ProtocolUserVerificationRequirement[keyof typeof ProtocolUserVerificationRequirement];


export function ProtocolUserVerificationRequirementFromJSON(json: any): ProtocolUserVerificationRequirement {
    return ProtocolUserVerificationRequirementFromJSONTyped(json, false);
}

export function ProtocolUserVerificationRequirementFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProtocolUserVerificationRequirement {
    return json as ProtocolUserVerificationRequirement;
}

export function ProtocolUserVerificationRequirementToJSON(value?: ProtocolUserVerificationRequirement | null): any {
    return value as any;
}

