/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProtocolCredentialDescriptor } from './ProtocolCredentialDescriptor';
import {
    ProtocolCredentialDescriptorFromJSON,
    ProtocolCredentialDescriptorFromJSONTyped,
    ProtocolCredentialDescriptorToJSON,
} from './ProtocolCredentialDescriptor';
import type { ProtocolUserVerificationRequirement } from './ProtocolUserVerificationRequirement';
import {
    ProtocolUserVerificationRequirementFromJSON,
    ProtocolUserVerificationRequirementFromJSONTyped,
    ProtocolUserVerificationRequirementToJSON,
} from './ProtocolUserVerificationRequirement';

/**
 * 
 * @export
 * @interface ProtocolPublicKeyCredentialRequestOptions
 */
export interface ProtocolPublicKeyCredentialRequestOptions {
    /**
     * 
     * @type {Array<ProtocolCredentialDescriptor>}
     * @memberof ProtocolPublicKeyCredentialRequestOptions
     */
    allowCredentials?: Array<ProtocolCredentialDescriptor>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ProtocolPublicKeyCredentialRequestOptions
     */
    challenge?: Array<number>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ProtocolPublicKeyCredentialRequestOptions
     */
    extensions?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof ProtocolPublicKeyCredentialRequestOptions
     */
    rpId?: string;
    /**
     * 
     * @type {number}
     * @memberof ProtocolPublicKeyCredentialRequestOptions
     */
    timeout?: number;
    /**
     * 
     * @type {ProtocolUserVerificationRequirement}
     * @memberof ProtocolPublicKeyCredentialRequestOptions
     */
    userVerification?: ProtocolUserVerificationRequirement;
}

/**
 * Check if a given object implements the ProtocolPublicKeyCredentialRequestOptions interface.
 */
export function instanceOfProtocolPublicKeyCredentialRequestOptions(value: object): boolean {
    return true;
}

export function ProtocolPublicKeyCredentialRequestOptionsFromJSON(json: any): ProtocolPublicKeyCredentialRequestOptions {
    return ProtocolPublicKeyCredentialRequestOptionsFromJSONTyped(json, false);
}

export function ProtocolPublicKeyCredentialRequestOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProtocolPublicKeyCredentialRequestOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'allowCredentials': json['allowCredentials'] == null ? undefined : ((json['allowCredentials'] as Array<any>).map(ProtocolCredentialDescriptorFromJSON)),
        'challenge': json['challenge'] == null ? undefined : json['challenge'],
        'extensions': json['extensions'] == null ? undefined : json['extensions'],
        'rpId': json['rpId'] == null ? undefined : json['rpId'],
        'timeout': json['timeout'] == null ? undefined : json['timeout'],
        'userVerification': json['userVerification'] == null ? undefined : ProtocolUserVerificationRequirementFromJSON(json['userVerification']),
    };
}

export function ProtocolPublicKeyCredentialRequestOptionsToJSON(value?: ProtocolPublicKeyCredentialRequestOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'allowCredentials': value['allowCredentials'] == null ? undefined : ((value['allowCredentials'] as Array<any>).map(ProtocolCredentialDescriptorToJSON)),
        'challenge': value['challenge'],
        'extensions': value['extensions'],
        'rpId': value['rpId'],
        'timeout': value['timeout'],
        'userVerification': ProtocolUserVerificationRequirementToJSON(value['userVerification']),
    };
}

