/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegistrationRequest
 */
export interface RegistrationRequest {
    /**
     * 
     * @type {string}
     * @memberof RegistrationRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationRequest
     */
    password_confirmation?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the RegistrationRequest interface.
 */
export function instanceOfRegistrationRequest(value: object): boolean {
    return true;
}

export function RegistrationRequestFromJSON(json: any): RegistrationRequest {
    return RegistrationRequestFromJSONTyped(json, false);
}

export function RegistrationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'] == null ? undefined : json['password'],
        'password_confirmation': json['password_confirmation'] == null ? undefined : json['password_confirmation'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function RegistrationRequestToJSON(value?: RegistrationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'password': value['password'],
        'password_confirmation': value['password_confirmation'],
        'username': value['username'],
    };
}

