/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    accessToken: string;
    /**
     * 
     * @type {number}
     * @memberof Token
     */
    expiresIn: number;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    idToken?: string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    issuedTokenType: string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    refreshToken: string;
    /**
     * 
     * @type {number}
     * @memberof Token
     */
    refreshTokenExpiresIn: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Token
     */
    scope: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    tokenType: string;
}

/**
 * Check if a given object implements the Token interface.
 */
export function instanceOfToken(value: object): boolean {
    if (!('accessToken' in value)) return false;
    if (!('expiresIn' in value)) return false;
    if (!('issuedTokenType' in value)) return false;
    if (!('refreshToken' in value)) return false;
    if (!('refreshTokenExpiresIn' in value)) return false;
    if (!('scope' in value)) return false;
    if (!('tokenType' in value)) return false;
    return true;
}

export function TokenFromJSON(json: any): Token {
    return TokenFromJSONTyped(json, false);
}

export function TokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Token {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'expiresIn': json['expires_in'],
        'idToken': json['id_token'] == null ? undefined : json['id_token'],
        'issuedTokenType': json['issued_token_type'],
        'refreshToken': json['refresh_token'],
        'refreshTokenExpiresIn': json['refresh_token_expires_in'],
        'scope': json['scope'],
        'tokenType': json['token_type'],
    };
}

export function TokenToJSON(value?: Token | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'access_token': value['accessToken'],
        'expires_in': value['expiresIn'],
        'id_token': value['idToken'],
        'issued_token_type': value['issuedTokenType'],
        'refresh_token': value['refreshToken'],
        'refresh_token_expires_in': value['refreshTokenExpiresIn'],
        'scope': value['scope'],
        'token_type': value['tokenType'],
    };
}

