/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TOTPWithSecret
 */
export interface TOTPWithSecret {
    /**
     * 
     * @type {Date}
     * @memberof TOTPWithSecret
     */
    createdAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof TOTPWithSecret
     */
    enabled: boolean;
    /**
     * 
     * @type {number}
     * @memberof TOTPWithSecret
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TOTPWithSecret
     */
    secret: string;
    /**
     * 
     * @type {number}
     * @memberof TOTPWithSecret
     */
    tenentId: number;
    /**
     * 
     * @type {Date}
     * @memberof TOTPWithSecret
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof TOTPWithSecret
     */
    userId: number;
}

/**
 * Check if a given object implements the TOTPWithSecret interface.
 */
export function instanceOfTOTPWithSecret(value: object): boolean {
    if (!('createdAt' in value)) return false;
    if (!('enabled' in value)) return false;
    if (!('id' in value)) return false;
    if (!('secret' in value)) return false;
    if (!('tenentId' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('userId' in value)) return false;
    return true;
}

export function TOTPWithSecretFromJSON(json: any): TOTPWithSecret {
    return TOTPWithSecretFromJSONTyped(json, false);
}

export function TOTPWithSecretFromJSONTyped(json: any, ignoreDiscriminator: boolean): TOTPWithSecret {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'enabled': json['enabled'],
        'id': json['id'],
        'secret': json['secret'],
        'tenentId': json['tenent_id'],
        'updatedAt': (new Date(json['updated_at'])),
        'userId': json['user_id'],
    };
}

export function TOTPWithSecretToJSON(value?: TOTPWithSecret | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'enabled': value['enabled'],
        'id': value['id'],
        'secret': value['secret'],
        'tenent_id': value['tenentId'],
        'updated_at': ((value['updatedAt']).toISOString()),
        'user_id': value['userId'],
    };
}

