/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TOTP
 */
export interface TOTP {
    /**
     * 
     * @type {Date}
     * @memberof TOTP
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof TOTP
     */
    secret: string;
    /**
     * 
     * @type {number}
     * @memberof TOTP
     */
    tenentId: number;
    /**
     * 
     * @type {Date}
     * @memberof TOTP
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof TOTP
     */
    userId: number;
}

/**
 * Check if a given object implements the TOTP interface.
 */
export function instanceOfTOTP(value: object): boolean {
    if (!('createdAt' in value)) return false;
    if (!('secret' in value)) return false;
    if (!('tenentId' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('userId' in value)) return false;
    return true;
}

export function TOTPFromJSON(json: any): TOTP {
    return TOTPFromJSONTyped(json, false);
}

export function TOTPFromJSONTyped(json: any, ignoreDiscriminator: boolean): TOTP {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'secret': json['secret'],
        'tenentId': json['tenent_id'],
        'updatedAt': (new Date(json['updated_at'])),
        'userId': json['user_id'],
    };
}

export function TOTPToJSON(value?: TOTP | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'secret': value['secret'],
        'tenent_id': value['tenentId'],
        'updated_at': ((value['updatedAt']).toISOString()),
        'user_id': value['userId'],
    };
}

