/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Email } from './Email';
import {
    EmailFromJSON,
    EmailFromJSONTyped,
    EmailToJSON,
} from './Email';
import type { PhoneNumber } from './PhoneNumber';
import {
    PhoneNumberFromJSON,
    PhoneNumberFromJSONTyped,
    PhoneNumberToJSON,
} from './PhoneNumber';

/**
 * 
 * @export
 * @interface UserWithPermissions
 */
export interface UserWithPermissions {
    /**
     * 
     * @type {number}
     * @memberof UserWithPermissions
     */
    applicationId: number;
    /**
     * 
     * @type {Date}
     * @memberof UserWithPermissions
     */
    createdAt: Date;
    /**
     * 
     * @type {Email}
     * @memberof UserWithPermissions
     */
    email?: Email;
    /**
     * 
     * @type {Array<Email>}
     * @memberof UserWithPermissions
     */
    emails: Array<Email>;
    /**
     * 
     * @type {number}
     * @memberof UserWithPermissions
     */
    id: number;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof UserWithPermissions
     */
    permissions: { [key: string]: Array<string>; };
    /**
     * 
     * @type {PhoneNumber}
     * @memberof UserWithPermissions
     */
    phoneNumber?: PhoneNumber;
    /**
     * 
     * @type {Array<PhoneNumber>}
     * @memberof UserWithPermissions
     */
    phoneNumbers: Array<PhoneNumber>;
    /**
     * 
     * @type {Date}
     * @memberof UserWithPermissions
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UserWithPermissions
     */
    username: string;
}

/**
 * Check if a given object implements the UserWithPermissions interface.
 */
export function instanceOfUserWithPermissions(value: object): boolean {
    if (!('applicationId' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('emails' in value)) return false;
    if (!('id' in value)) return false;
    if (!('permissions' in value)) return false;
    if (!('phoneNumbers' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('username' in value)) return false;
    return true;
}

export function UserWithPermissionsFromJSON(json: any): UserWithPermissions {
    return UserWithPermissionsFromJSONTyped(json, false);
}

export function UserWithPermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWithPermissions {
    if (json == null) {
        return json;
    }
    return {
        
        'applicationId': json['application_id'],
        'createdAt': (new Date(json['created_at'])),
        'email': json['email'] == null ? undefined : EmailFromJSON(json['email']),
        'emails': ((json['emails'] as Array<any>).map(EmailFromJSON)),
        'id': json['id'],
        'permissions': json['permissions'],
        'phoneNumber': json['phone_number'] == null ? undefined : PhoneNumberFromJSON(json['phone_number']),
        'phoneNumbers': ((json['phone_numbers'] as Array<any>).map(PhoneNumberFromJSON)),
        'updatedAt': (new Date(json['updated_at'])),
        'username': json['username'],
    };
}

export function UserWithPermissionsToJSON(value?: UserWithPermissions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'application_id': value['applicationId'],
        'created_at': ((value['createdAt']).toISOString()),
        'email': EmailToJSON(value['email']),
        'emails': ((value['emails'] as Array<any>).map(EmailToJSON)),
        'id': value['id'],
        'permissions': value['permissions'],
        'phone_number': PhoneNumberToJSON(value['phoneNumber']),
        'phone_numbers': ((value['phoneNumbers'] as Array<any>).map(PhoneNumberToJSON)),
        'updated_at': ((value['updatedAt']).toISOString()),
        'username': value['username'],
    };
}

