/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WebauthncoseCOSEAlgorithmIdentifier = {
    AlgES256: -7,
    AlgES384: -35,
    AlgES512: -36,
    AlgRS1: -65535,
    AlgRS256: -257,
    AlgRS384: -258,
    AlgRS512: -259,
    AlgPS256: -37,
    AlgPS384: -38,
    AlgPS512: -39,
    AlgEdDSA: -8,
    AlgES256K: -47
} as const;
export type WebauthncoseCOSEAlgorithmIdentifier = typeof WebauthncoseCOSEAlgorithmIdentifier[keyof typeof WebauthncoseCOSEAlgorithmIdentifier];


export function WebauthncoseCOSEAlgorithmIdentifierFromJSON(json: any): WebauthncoseCOSEAlgorithmIdentifier {
    return WebauthncoseCOSEAlgorithmIdentifierFromJSONTyped(json, false);
}

export function WebauthncoseCOSEAlgorithmIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebauthncoseCOSEAlgorithmIdentifier {
    return json as WebauthncoseCOSEAlgorithmIdentifier;
}

export function WebauthncoseCOSEAlgorithmIdentifierToJSON(value?: WebauthncoseCOSEAlgorithmIdentifier | null): any {
    return value as any;
}

