/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Errors,
  ModelValidateMFAST,
  Token,
  TokenRequest,
} from '../models/index';
import {
    ErrorsFromJSON,
    ErrorsToJSON,
    ModelValidateMFASTFromJSON,
    ModelValidateMFASTToJSON,
    TokenFromJSON,
    TokenToJSON,
    TokenRequestFromJSON,
    TokenRequestToJSON,
} from '../models/index';

export interface CreateTokenRequest {
    tokenRequest: TokenRequest;
}

export interface ValidateMfaRequest {
    mfa: ModelValidateMFAST;
}

/**
 * TokenApi - interface
 * 
 * @export
 * @interface TokenApiInterface
 */
export interface TokenApiInterface {
    /**
     * 
     * @summary Create JWT Token
     * @param {TokenRequest} tokenRequest token request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApiInterface
     */
    createTokenRaw(requestParameters: CreateTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>>;

    /**
     * Create JWT Token
     */
    createToken(tokenRequest: TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token>;

    /**
     * Multi-factor authentication
     * @summary Multi-factor authentication
     * @param {ModelValidateMFAST} mfa mfa validation
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApiInterface
     */
    validateMfaRaw(requestParameters: ValidateMfaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>>;

    /**
     * Multi-factor authentication
     * Multi-factor authentication
     */
    validateMfa(mfa: ModelValidateMFAST, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token>;

}

/**
 * 
 */
export class TokenApi extends runtime.BaseAPI implements TokenApiInterface {

    /**
     * Create JWT Token
     */
    async createTokenRaw(requestParameters: CreateTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>> {
        if (requestParameters['tokenRequest'] == null) {
            throw new runtime.RequiredError(
                'tokenRequest',
                'Required parameter "tokenRequest" was null or undefined when calling createToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Tenent-Id"] = await this.configuration.apiKey("Tenent-Id"); // TenentId authentication
        }

        const response = await this.request({
            path: `/token`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenRequestToJSON(requestParameters['tokenRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     * Create JWT Token
     */
    async createToken(tokenRequest: TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token> {
        const response = await this.createTokenRaw({ tokenRequest: tokenRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Multi-factor authentication
     * Multi-factor authentication
     */
    async validateMfaRaw(requestParameters: ValidateMfaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>> {
        if (requestParameters['mfa'] == null) {
            throw new runtime.RequiredError(
                'mfa',
                'Required parameter "mfa" was null or undefined when calling validateMfa().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Authorization authentication
        }

        const response = await this.request({
            path: `/mfa`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelValidateMFASTToJSON(requestParameters['mfa']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     * Multi-factor authentication
     * Multi-factor authentication
     */
    async validateMfa(mfa: ModelValidateMFAST, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token> {
        const response = await this.validateMfaRaw({ mfa: mfa }, initOverrides);
        return await response.value();
    }

}
